version: '3.0'
services:
  pokemons:
    build: ./dockerfiles/python
    image: pokemons
    container_name: pokemons
    hostname: pokemons
    restart: always
    volumes:
      - './pokemons:/service'
    command: python3 /service/pokemons.py
    ports:
      - '5001:5000'
  comments:
    build: ./dockerfiles/python
    image: comments
    container_name: comments
    hostname: comments
    restart: always
    volumes:
      - './comments:/service'
    command: python3 /service/comments.py
    ports:
      - '5002:5000'
  likes:
    build: ./dockerfiles/python
    image: likes
    container_name: likes
    hostname: likes
    restart: always
    volumes:
      - './likes:/service'
    command: python3 /service/likes.py
    ports:
      - '5003:5000'
  database:
    image: mysql
    container_name: database
    hostname: database
    restart: always
    ports:
      - '5004:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=pokeinfo
  files:
    image: files
    build: ./dockerfiles/nginx
    container_name: files
    hostname: files
    restart: always
    volumes:
      - './images:/usr/share/nginx/html'
    ports:
      - '5005:80'
